language: node_js
node_js: node

before_script:
  - npm ci
  - ( cd projects/lib && npm ci )
  - npx prettier --check .
  - npx eslint --ext ts --max-warnings 0 .
script:
  - npx ng build
  - npx ng build --prod
after_success:
  - set -e
  - out=`git status --porcelain`; [ -z "$out" ] || ( git diff; exit 1 )

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${DEPLOY_NPM_TOKEN}" > "$HOME/.npmrc"
deploy:
  - provider: script
    script: cd dist/lib && npm version prerelease --preid=p`date +%Y%m%d%H%M%S` && npm publish --tag dev --access public
    skip_cleanup: true
    on:
      branch: main
  - provider: script
    script: cd dist/lib && npm publish --access public
    skip_cleanup: true
    on:
      tags: true
